### PR TITLE
new icon

### PR DESCRIPTION
**Pull request by Mptied**

### CODE REVIEW

**Comment by OpenSauce04** [comment]
Why is the `a` back, I thought we ditched that?

**Comment by jebbyk** [comment]
@Mptied  We are decided to get rid of 'a'

**Review by jebbyk — CHANGES_REQUESTED** [review]
I suggest to remove an 'a' letter from icon

**Comment by Mptied** [comment]
but why...? aren't it supposed to mark the version as beta, as you've requested before?

**Pull request merged**
