### PR TITLE
Variable corrections 2

### PR DESCRIPTION
**Pull request by OpenSauce04**
### Summary:

- Corrected the name of `TONEMAPPING_GAMMA` to `TONE_MAPPING_GAMMA` to be consistent with other tonemapping variable names
- Renamed all instances of "blue fog" with "distance fog", as that is what it is actually called

### CODE REVIEW

**Comment by OpenSauce04** [comment]
Marking this as a draft because I haven't tested it yet
Will undraft when I have

**Comment by jebbyk** [comment]
I've checked it on my phone. It works normally.

**Comment by jebbyk** [comment]
all looks good to me, if you have nothing to add I gonna merge it

**Comment by OpenSauce04** [comment]
I have nothing else to add, go ahead :)

**Pull request merged**
