### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by fredster33**
Grammar fixes, as well as adding a contributor code of conduct.

### CODE REVIEW

**Comment by OpenSauce04** [comment]
Check my PR on your fork, I made another small change and decided to append it to this rather than make a whole new one

**Comment by fredster33** [comment]
@OpenSauce04 merged.

**Review by jebbyk — COMMENTED** [review]
@fredster33 I think it is better to keep 8th line in readme because probably not so much people's are familiar with termux or others linux terminals. What do you think? And also you can add yourself to developers list btw. check out .json files in this pack.

**Comment by fredster33** [comment]
> @fredster33 I think it is better to keep 8th line in readme because probably not so much people's are familiar with termux or others linux terminals. What do you think? And also you can add yourself to developers list btw. check out .json files in this pack.

I believe that it would be potentially beneficial. Over the next few days, I'll try to add some more information on installation.

**Comment by jebbyk** [comment]
ok I'll merge when you ready

**Comment by OpenSauce04** [comment]
> @fredster33 I think it is better to keep 8th line in readme because probably not so much people's are familiar with termux or others linux terminals. What do you think? And also you can add yourself to developers list btw. check out .json files in this pack.

If they are that unfamiliar, they probably shouldn't be working on this in the first place
Besides my previous point still stands that most people will be working on this from a computer, and termux isn't even available on PC

**Comment by fredster33** [comment]
> > @fredster33 I think it is better to keep 8th line in readme because probably not so much people's are familiar with termux or others linux terminals. What do you think? And also you can add yourself to developers list btw. check out .json files in this pack.
> 
> If they are that unfamiliar, they probably shouldn't be working on this in the first place
> Besides my previous point still stands that most people will be working on this from a computer, and termux isn't even available on PC

I think that this repo should be a welcoming place for any contributor, even new ones. I will add more details on contributing on all platforms in the following days.

**Comment by jebbyk** [comment]
@fredster33 should I merge it or you want to add somehting else?

**Comment by fredster33** [comment]
> @fredster33 should I merge it or you want to add somehting else?

Please merge it for now, I'll submit another PR if needed.

**Pull request merged**
