### PR TITLE
Removed vanilla water animation

### PR DESCRIPTION
**Pull request by OpenSauce04**
Removed the pixelated water animation left over by the base game from the pack, which makes the water look significantly cleaner from the side than it did before (kind of hard to see in the screenshot, but it's really obivious in-game)

Before:
Screenshot from 2021-05-02 13-24-44

After
Screenshot from 2021-05-02 13-28-50

### CODE REVIEW

**Comment by OpenSauce04** [comment]
The really large number of files changed is because of the metadata cleanup I did
You can check the actual changes here: https://github.com/jebbyk/OSBES-minecraft-bedrock-edition-shader/pull/143/commits/ea27da11881404dcdfacc667b9d93ce1fd5dc1ad

**Comment by OpenSauce04** [comment]
By the way just to be clear the lack of white stuff on the "new" picture isn't a change, it was just a coincidence.

**Comment by jebbyk** [comment]
Are you sure it is a good idea? sometimes it indicates direction of water movement.

**Comment by OpenSauce04** [comment]
> Are you sure it is a good idea? sometimes it indicates direction of water movement. 

Yeah, it looks really janky and it's never really hard to tell which way the water's going anyway.

**Comment by jebbyk** [comment]
ok I gonna check it on my phone and merge if it is ok

**Comment by OpenSauce04** [comment]
You going to merge it?

**Pull request merged**
