### PR TITLE
Sky colour adjustments

### PR DESCRIPTION
**Pull request by OpenSauce04**
I've made a few changes to the sky to make it look a bit more vibrant and appealing when compared to how it was before. For example, making the main sky a more saturated blue and adding a slight tint of purple to the sunset.

---------------
Before:
Screenshot from 2021-05-01 13-09-04
Screenshot from 2021-05-01 13-09-09
Screenshot from 2021-05-01 13-09-38
---------------

After:
Screenshot from 2021-05-02 14-33-01
image
image

------------

(The After pictures look a little more zoomed in because they were taken on a 16:9 monitor, whereas the before pictures were taken on an ultrawide monitor)

### CODE REVIEW

**Comment by OpenSauce04** [comment]
Merged with #148

**Comment by jebbyk** [comment]
IMO it does not looking good. I dont think sky can be so saturated and purple at sunset

**Comment by jebbyk** [comment]
Clouds can be. Not the sky 
So here the sky
image

**Comment by jebbyk** [comment]
Clouds
image

**Comment by OpenSauce04** [comment]
> IMO it does not looking good. I dont think sky can be so saturated and purple at sunset

That was actually a suggestion I followed through with. Beforehand, it looked like this
image
Is this better IYO? (with a little more orange maybe)

**Comment by OpenSauce04** [comment]
Final sunset revision
Screenshot from 2021-05-16 16-53-13

**Comment by jebbyk** [comment]
Finally I think there is no need to merge it because those paramenters will be in settings file when presets are ready

**Comment by OpenSauce04** [comment]
> Finally I think there is no need to merge it because those paramenters will be in settings file when presets are ready

I'll believe it when I see it

**Comment by jebbyk** [comment]
now I can say "soon" ive found a problem with padding so I can at least add new textures

**Comment by OpenSauce04** [comment]
Presets broke this PR, will redo

**Pull request closed without merging**
